export default {
  products: [
    {
      _id:'111111111111111111111111',
      name: 'Chocolate Coconut Bar',
      category: 'Snacks',
      image: './images/Bounty-Chocolate.jpg',
      price: 4.99,
      brand: 'Bounty',
      rating: 3.5,
      numOfReviews: 9,
      countInStock: 0,
      description:' Two bars per pack. Imported from England. Bounty is a chocolate bar manufactured by Mars, Incorporated and sold internationally. It has a coconut filling covered with milk chocolate (sold in a blue wrapper).'
    },
    {
      _id:'222222222222222222222222',
      name: 'Unica Wafers 24 count 28.5 oz.',
      category: 'Snacks',
      image: './images/Unica-Wafers.jpg',
      price: 11.99,
      brand: 'Gandour',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 55,
      description:'A Middle Eastern snack people have loved since they were a kid. Made by the famous Gandour company in Lebanon, these crispy wafers are coated with a milky chocolate sensation.'
    },
    {
      _id:'333333333333333333333333',
      name: 'Milk Chocolate 10 Bar Pack',
      category: 'Snacks',
      image: './images/Choceur-MilkChoc.jpg',
      price: 11.99,
      brand: 'Choceur',
      rating: 5.0,
      numOfReviews: 25,
      countInStock: 65,
    },
    {
      _id:'444444444444444444444444',
      name: 'French Baguette',
      category: 'Accessories',
      image: './images/BaguetteLARPWeapon.jpg',
      price: 45.99,
      brand: 'Nemesis',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 55,
    },
    /* Malachite Protection Source Pendant */
    {
      _id:'555555555555555555555555',
      name: 'Malachite Protection Source Pendant',
      category: 'Accessories',
      image: './images/malachite-protection-source-pendant-pendants-862_1728x.jpg',
      price: 49.99,
      brand: 'Qi Life',
      rating: 3.0,
      numOfReviews: 10,
      countInStock: 55,
    },
  ],
};
