export default {
  products: [
    {
      id: '1',
      name: 'Chocolate Coconut Bar',
      category: 'Snacks',
      image: './images/Bounty-Chocolate.jpg',
      price: 4.99,
      brand: 'Bounty',
      rating: 3.5,
      numOfReviews: 9,
      countInStock: 0,
    },
    {
      id: '2',
      name: 'Unica Wafers 24 count 28.5 oz.',
      category: 'Snacks',
      image: './images/Unica-Wafers.jpg',
      price: 11.95,
      brand: 'Gandour',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 55,
    },
    {
      id: '3',
      name: 'Milk Chocolate 10 Bar Pack',
      category: 'Snacks',
      image: './images/Choceur-MilkChoc.jpg',
      price: 11.95,
      brand: 'Choceur',
      rating: 5.0,
      numOfReviews: 25,
      countInStock: 65,
    },
    {
      id: '4',
      name: 'French Baguette',
      category: 'Accessories',
      image: './images/BaguetteLARPWeapon.jpg',
      price: 45.95,
      brand: 'Nemesis',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 55,
    },
    /* Malachite Protection Source Pendant */
    {
      id: '5',
      name: 'Malachite Protection Source Pendant',
      category: 'Accessories',
      image: './images/malachite-protection-source-pendant-pendants-862_1728x.jpg',
      price: 49.99,
      brand: 'Qi Life',
      rating: 3.0,
      numOfReviews: 10,
      countInStock: 55,
    },
  ],
};
